### PR TITLE
Add configuration and support to build binary executable

### PR DESCRIPTION
**Pull request by DanielJoyce**
Since we are using setup.cfg, removed requirements.txt

Updated core dependencies

Added optional dependencies to setup.cfg, and script to build a single file binary.

Expanded documentation.

### CODE REVIEW

**Comment by DanielJoyce** [comment]
Single file executable size is 11mb. Could probably make smaller by stripping.

**Comment by philipl** [comment]
Hi Daniel. Thanks for the various improvements here. I'll need to some time to go over it.

**Comment by philipl** [comment]
This looks good. Can you squash the commits into separate logical changes for the static build, updating dependencies, and updating the documentation?

Thanks!

**Comment by DanielJoyce** [comment]
Sorry, been a while since I checked this. Will do in a bit. Should get around to it sometime this week

**Comment by DanielJoyce** [comment]
Marking this as draft for second PR with squashed commits.

**Comment by philipl** [comment]
Replaced by #27

**Pull request closed without merging**
